apiVersion: v2
appVersion: 1.4.0
name: gateway-api-config
description: Default configuration for Envoy Gateway
home: https://github.com/giantswarm/gateway-api-config-app
icon: https://s.giantswarm.io/app-icons/gateway-api/1/light.svg
version: 1.4.0
annotations:
  application.giantswarm.io/team: team-cabbage
