{{- define "gatewayClassEnvoyProxyValuesDefault" }}
envoyPDB:
  maxUnavailable: "25%"
envoyHpa:
  minReplicas: 2
  maxReplicas: 10
envoyDeployment:
  container:
    imageRepository: gsoci.azurecr.io/giantswarm/envoy
{{- end }}

{{- range $i, $class := .Values.gatewayClasses }}
{{- if and $class.enabled $class.envoyProxy.enabled }}
{{- $envoyProxyValues := (include "gatewayClassEnvoyProxyValuesDefault" $ ) | fromYaml -}}
{{- $customEnvoyProxyValues := $class.envoyProxy -}}
{{- if $customEnvoyProxyValues -}}
{{- $envoyProxyValues = mergeOverwrite $envoyProxyValues (deepCopy $customEnvoyProxyValues) -}}
{{- end }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gatewayclass-{{ $class.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  {{- include "envoyProxy.spec" $envoyProxyValues | nindent 2 }}
{{- end }}
{{- end }}
