{{- define "gatewayClassEnvoyProxyValuesDefault" }}
envoyPDB:
  maxUnavailable: "25%"
envoyHpa:
  minReplicas: 2
  maxReplicas: 10
envoyDeployment:
  container:
    imageRepository: gsoci.azurecr.io/giantswarm/envoy
{{- end }}

{{- range $i, $class := .Values.gatewayClasses }}
{{- if and $class.enabled $class.envoyProxy.enabled }}
{{- $envoyProxyValues := (include "gatewayClassEnvoyProxyValuesDefault" $ ) | fromYaml -}}
{{- $customEnvoyProxyValues := $class.envoyProxy -}}
{{- if $customEnvoyProxyValues -}}
{{- $envoyProxyValues = mergeOverwrite $envoyProxyValues (deepCopy $customEnvoyProxyValues) -}}
{{- end -}}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gatewayclass-{{ $class.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      {{- with $envoyProxyValues.envoyDeployment }}
      envoyDeployment:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $envoyProxyValues.envoyService }}
      envoyService:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $envoyProxyValues.envoyHpa }}
      envoyHpa:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $envoyProxyValues.envoyPDB }}
      envoyPDB:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $envoyProxyValues.envoyServiceAccount }}
      envoyServiceAccount:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with $envoyProxyValues.logging }}
  logging:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.telemetry }}
  telemetry:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.bootstrap }}
  bootstrap:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.concurrency }}
  concurrency:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.extraArgs }}
  extraArgs:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.mergeGateways }}
  mergeGateways:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.shutdown }}
  shutdown:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
{{- end }}
