{{- range $i, $gateway := .Values.gateways }}
{{- if $gateway.enabled }}
{{- if and (eq $.Values.provider "capa") $gateway.provider.aws.useNetworkLoadBalancer }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: gateway-{{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ $gateway.name }}
  proxyProtocol:
    optional: false
  healthCheck:
    path: /healthz
{{- end }}
{{- end }}
{{- end }}
