{{- define "gatewayEnvoyProxyValuesDefault" }}
envoyPDB:
  maxUnavailable: "25%"
envoyHpa:
  minReplicas: 2
  maxReplicas: 10
envoyDeployment:
  container:
    imageRepository: gsoci.azurecr.io/giantswarm/envoy
{{- end }}

{{- range $i, $gateway := .Values.gateways }}
{{- if and $gateway.enabled $gateway.envoyProxy.enabled }}
{{- if not $gateway.service }}
{{- $_ := set $gateway "service" dict }}
{{- end }}
{{- $envoyProxyValues := (include "gatewayEnvoyProxyValuesDefault" $ ) | fromYaml -}}
{{- $customEnvoyProxyValues := $gateway.envoyProxy -}}
{{- if $customEnvoyProxyValues -}}
{{- $envoyProxyValues = mergeOverwrite $envoyProxyValues (deepCopy $customEnvoyProxyValues) -}}
{{- end -}}
{{- $envoyServiceDefaults := (include "gateway.envoyServiceDefaults" (dict "provider" $.Values.provider "baseDomain" $.Values.baseDomain "gateway" $gateway "root" $)) | fromYaml -}}
{{- $_ := set $envoyProxyValues "envoyService" (mergeOverwrite $envoyServiceDefaults (deepCopy (default dict $envoyProxyValues.envoyService))) -}}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gateway-{{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  {{- include "gateway.shutdown" (dict "provider" $.Values.provider "gateway" $gateway) | nindent 2 }}
  provider:
    type: Kubernetes
    kubernetes:
      {{- with $envoyProxyValues.envoyDeployment }}
      envoyDeployment:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $envoyProxyValues.envoyService }}
      envoyService:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $envoyProxyValues.envoyHpa }}
      envoyHpa:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $envoyProxyValues.envoyPDB }}
      envoyPDB:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $envoyProxyValues.envoyServiceAccount }}
      envoyServiceAccount:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with $envoyProxyValues.logging }}
  logging:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.telemetry }}
  telemetry:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.bootstrap }}
  bootstrap:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.concurrency }}
  concurrency:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.extraArgs }}
  extraArgs:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with $envoyProxyValues.mergeGateways }}
  mergeGateways:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
{{- end }}
