{{- define "gatewayEnvoyProxyValuesDefault" }}
envoyPDB:
  maxUnavailable: "25%"
envoyHpa:
  minReplicas: 2
  maxReplicas: 10
envoyDeployment:
  container:
    imageRepository: gsoci.azurecr.io/giantswarm/envoy
{{- end }}

{{- range $i, $gateway := .Values.gateways }}
{{- if and $gateway.enabled $gateway.envoyProxy.enabled }}
{{- if not $gateway.service }}
{{- $_ := set $gateway "service" dict }}
{{- end }}
{{- $envoyProxyValues := (include "gatewayEnvoyProxyValuesDefault" $ ) | fromYaml -}}
{{- $customEnvoyProxyValues := $gateway.envoyProxy -}}
{{- if $customEnvoyProxyValues -}}
{{- $envoyProxyValues = mergeOverwrite $envoyProxyValues (deepCopy $customEnvoyProxyValues) -}}
{{- end -}}
{{- $envoyServiceDefaults := (include "gateway.envoyServiceDefaults" (dict "provider" $.Values.provider "baseDomain" $.Values.baseDomain "gateway" $gateway "root" $)) | fromYaml -}}
{{- $_ := set $envoyProxyValues "envoyService" (mergeOverwrite $envoyServiceDefaults (deepCopy (default dict $envoyProxyValues.envoyService))) -}}
{{- $shutdownDefaults := (include "gateway.shutdownDefaults" (dict "provider" $.Values.provider "gateway" $gateway)) | fromYaml -}}
{{- if $shutdownDefaults -}}
{{- $_ := set $envoyProxyValues "shutdown" (mergeOverwrite $shutdownDefaults (deepCopy (default dict $envoyProxyValues.shutdown))) -}}
{{- end -}}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gateway-{{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  {{- include "envoyProxy.spec" $envoyProxyValues | nindent 2 }}
{{- end }}
{{- end }}
