{{- range $i, $gateway := .Values.gateways }}
{{- if $gateway.enabled }}
{{- if $gateway.envoyProxy.enabled }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: gateway-{{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  {{- include "gateway.shutdown" (dict "provider" $.Values.provider "gateway" $gateway) | nindent 2 }}
  provider:
    type: Kubernetes
    {{- if $gateway.service }}
    kubernetes:
      {{- with $gateway.envoyProxy.envoyDeployment }}
      envoyDeployment:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      envoyService:
        loadBalancerClass: {{ include "service.loadBalancerClass" (dict "provider" $.Values.provider "gateway" $gateway) }}
        externalTrafficPolicy: {{ include "service.externalTrafficPolicy" (dict "provider" $.Values.provider "gateway" $gateway) }}
        {{- with $gateway.service.labels }}
        labels:
          {{- (tpl (. | toYaml | toString ) $) | nindent 10 }}
        {{- end }}
        annotations:
          {{- include "service.annotations" (dict "provider" $.Values.provider "baseDomain" $.Values.baseDomain "gateway" $gateway) | nindent 10 }}
      {{- with $gateway.envoyProxy.envoyHpa }}
      envoyHpa:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $gateway.envoyProxy.envoyPDB }}
      envoyPDB:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $gateway.envoyProxy.envoyServiceAccount }}
      envoyServiceAccount:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
{{- if eq $.Values.provider "capa" }}
{{- if $gateway.provider.aws.useNetworkLoadBalancer }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: gateway-{{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ $gateway.name }}
  proxyProtocol:
    optional: false
  healthCheck:
    path: /healthz
{{- end }}
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gateway.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    {{- with $gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ $gateway.className }}
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: gateway-{{ $gateway.name }}
      namespace: {{ $.Release.Namespace }}
  listeners:
    {{- range $k, $l:= $gateway.listeners }}
    - name: {{ $l.name }}
      protocol: {{ $l.protocol }}
      port: {{ $l.port }}
      {{- with $l.allowedRoutes }}
      allowedRoutes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $l.hostname }}
      hostname: {{ tpl (. | quote) $ }}
      {{- end }}
      {{- with $l.tls }}
      tls:
        mode: {{ .mode }}
        {{- if or (.certificateRefs) ($l.certificate.enabled) }}
        certificateRefs:
        {{- if and (eq .mode "Terminate") ($l.certificate.enabled) }}
        - kind: Secret
          name: {{ printf "gateway-%s-%s-tls" $gateway.name $l.name }}
        {{- end }}
        {{- range .certificateRefs }}
        - kind: Secret
          name: {{ .name }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
