{{- range $i, $gateway := .Values.gateways }}
{{- if $gateway.enabled }}
{{- if $gateway.tlsIssuer.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $gateway.tlsIssuer.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  acme:
    email: {{ $gateway.tlsIssuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ $gateway.tlsIssuer.name }}
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: {{ $gateway.tlsIssuer.gateway }}
            namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
